[target.aarch64-unknown-linux-gnu]
linker = "/gcc-10.2.1-20210303-sigmastar-glibc-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc"
ar = "/gcc-10.2.1-20210303-sigmastar-glibc-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-ar"
rustflags = ["-C", "link-arg=-s"]

[env]
BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu = "--sysroot=/gcc-10.2.1-20210303-sigmastar-glibc-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc"
LIBCLANG_PATH = "/usr/lib/llvm-10/lib"

[profile.release]
opt-level = "z"          # 优化大小而非速度
lto = true               # 启用链接时优化
codegen-units = 1        # 减少代码生成单元以获得更好的优化
panic = "abort"          # 使用 abort 而非 unwind 减小大小
strip = true             # 剥离符号表和调试信息
